import sys


help = '''
python getRandomData.py   input.data    output.dat
        input.data      input file name. random data directly generated by spectre(copy from file 'monteCarlo/compactmismatchdata)
        output.dat      output file name. formative random data file. 
    note: the last line of outputfile is input mean.
'''

def formativeData(input = 'tmpRandom.data' , output = 'randomData.dat'):
    f = open(input)
    o = open(output,'w')
    lines = f.readlines()
    for x in lines:
        x = x.strip()
        if x == '' :
            continue
        elif x[0] == ' ' or x[0]== '#':
            continue
        else:
            o.write(x)
            o.write('\n')
            
 
'''
f = open('randomh0.data')
lines = f.readlines()
#print(lines)
for x in range(2000):
    print(lines[3*x + 1],end=',')
'''

if __name__ == "__main__":
    for x in sys.argv:
        if x == '-h':
            print(help)
            exit(0)
    formativeData(sys.argv[1] , sys.argv[2])
    print(sys.argv)




print('The end')
